### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by alerque** [ActuallyAllie/cli-clipboard#13]
Downstream projects are depending on the Git HEAD version which is causing a problem for packaging. Please cut a new release so there is a stable tag with a working build downstream projects can depend on. Thanks.

**Comment by alerque** [comment]
e.g. https://github.com/magic-wormhole/magic-wormhole.rs/blob/0a971831c61b6559c773702d169479b20a5638d1/cli/Cargo.toml#L25

**Comment by xen0n** [comment]
Yeah definitely we need a release. `xcb` vulnerabilities are bugging many of us and the current crates.io version doesn't bring `xcb > 1.0`.
