### ISSUE TITLE
Docs mention `set_contents_for_duration`

### ISSUE THREAD

**Issue by rope-hmg** [ActuallyAllie/cli-clipboard#7]
Docs mention `set_contents_for_duration`, but the linked page doesn't exist and I couldn't see it in the crate src.

**Comment by rope-hmg** [comment]
It's mentioned here: https://docs.rs/cli-clipboard/latest/cli_clipboard/fn.set_contents.html
There is a link in the documentation to https://docs.rs/cli-clipboard/latest/cli_clipboard/fn.set_contents_for_duration.html, but that page doesn't exist and I had a look through the source and couldn't find any reference either.

I don't think the timeout thing would work for my case. I mean, I could use it, but it'd probably be annoying for the use case I have. I have a silly cli app that generates takes some text from `stdin` and changes it into emoji for pasting into discord. At the moment I just have it printing to `stdout` since the clipboard is cleared when the app closes.

**Comment by ActuallyAllie** [comment]
Thanks, I'll remove the reference from the docs then.  Yea, it's definitely annoying to build the way I did, but I couldn't come up with another solution that worked cross platform.  I remember looking into fork and similar things a lot when trying to do it, but ultimately all of the other solutions I found either didn't work on 1 or 2 of the platforms or were really hacky.  

If you are able to come up with something I'd consider including it here as it would be a nice feature for this library. The solution I used doesn't really work for a library unfortunately.

If you just want to get it over with though and have your app close and keep the emoji in the clipboard, I would recommend trying out my code above.  It seems like a huge pain, but really you just need to accept a subcommand like `clip` ie `text-to-emoji clip` that calls the second fn.  The first function is then called when you want to copy the emoji to the clipboard. It's kind of silly but it works :woman_shrugging:

**Comment by rope-hmg** [comment]
That's a shame. I don't mind a Linux only solution. The code is only a few tens of lines long.

Thanks for the help though.

**Comment by ActuallyAllie** [comment]
Oh, for your use case you should probably just make a bash or zsh function and use xclip or wl-copy.  This could be wildly incorrect but a simple example based on some function i have in my .zshrc:

Definition
```
function emoji() {
    text-to-emoji "$@" | wl-copy
}
```

Usage
```
emoji shrugging
```

**Comment by rope-hmg** [comment]
I hadn't thought of that. I'll give that a go. Thanks
