### ISSUE TITLE
Is there a CLI?

### ISSUE THREAD

**Issue by xeruf** [ActuallyAllie/cli-clipboard#8]
The name seems a little misleading, as this seems to be a library rather than a usable CLI. Do you know of a CLI that does this?
I found https://github.com/penguingovernor/beeclip but it is rather a unmaintained prototype.

**Comment by piegamesde** [comment]
This is intended for usage in CLI applications, not a CLI application itself. Of course it would be really easy to add a simple `clap` application and put it in the examples folder or something.
